name: Dependabot auto-merge

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.1.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: dependabot
          wait-interval: 15

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Enable auto-merge for Dependabot PRs
        if: >-
          ${{steps.metadata.outputs.update-type == 'version-update:semver-patch'
          || contains(steps.metadata.outputs.dependency-names, '@types')}}
          || contains(steps.metadata.outputs.dependency-names, 'commitlint')}}
          || contains(steps.metadata.outputs.dependency-names, 'eslint')}}
          || contains(steps.metadata.outputs.dependency-names, 'webpack')}}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
